name: Deploy to Hosting (FTP)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Path tới thư mục chứa source code trên hosting (Ví dụ: iNet Hostings) 
          # Lưu ý: Do FTP User đã trỏ sẵn vào /home/ndoagugnhosting/domains/onetask.1pixel.vn/
          # Nên server-dir để ./ để upload trực tiếp vào thư mục root này.
          server-dir: ./
          protocol: ftps
          port: 21
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/
            .gitignore
